services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: container-registry.oracle.com/database/free:latest
    environment:
      ORACLE_PWD: password
      ORACLE_SID: FREE
      ORACLE_CHARACTERSET: AL32UTF8
